#!/usr/bin/env node

/**
 * Module dependencies.
 */

// var app = require('../app');
var debug = require('debug')('webGL_3d_modeling:server');
var http = require('http'),
  https = require('https'),
  fs = require('fs'),
  path = require('path'),
  logger = require('morgan'),
  cookieParser = require('cookie-parser'),
  bodyParser = require('body-parser'),
  express = require('express'),
  routes = require('./routes/index'),
  users = require('./routes/users'),
  api = require('./routes/api'),
  lessMiddleware = require('less-middleware'),
  options = {
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem')
};

/**
 * Get port from environment and store in Express.
 */

var port2 = 50000;

/**
 * Create HTTP server.
 */

var app = express();

app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(bodyParser.json());


https.createServer(options, app).listen(port2, function(){
  console.log("Https server listening on port " + port2);
});

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());

app.use(lessMiddleware(
    path.join(__dirname, '/public', 'stylesheets', 'less'), // source
    { 
      dest: path.join(__dirname, '/public', 'stylesheets', 'css'),
      debug: true, 
    } 
));

app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);
app.use('/api', api);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});
